version: '3.9'
services:
  vllm:
    image: nvidia/cuda:12.2.0-base-ubuntu22.04
    container_name: vllm-server
    environment:
      - HF_TOKEN=${HF_TOKEN}
    volumes:
      - ./models:/mnt/models
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: >
      bash -c "pip install vllm && python3 -m vllm.entrypoints.openai.api_server --host 0.0.0.0 --port 8000 --model /mnt/models/your-model"

  app:
    build:
      context: .
      dockerfile: Dockerfile.gpu
    container_name: localtrans-app
    environment:
      - USE_GPU=1
      - USE_VLLM=1
      - HF_TOKEN=${HF_TOKEN}
    volumes:
      - .:/workspace
      - ./models:/mnt/models
    working_dir: /workspace
    depends_on:
      - vllm
    tty: true
    stdin_open: true
